import Navbar from "@/sections/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <nav>
          <Navbar />
        </nav> */}
        <div>{children}</div>
      </body>
    </html>
  );
}
